package nl.craftsmen.baristaorder.persistence;

import nl.craftsmen.baristaorder.core.Order;
import nl.craftsmen.baristaorder.core.OrdersProvider;
import org.springframework.data.repository.CrudRepository;
import org.springframework.stereotype.Repository;

@Repository
public interface OrdersRepository extends CrudRepository<OrderEntity, Long>, OrdersProvider {

    default Order saveOrder(Order order) {
        var orderEntity = OrderMapper.toEntity(order);
        save(orderEntity);
        return OrderMapper.fromEntity(orderEntity);
    }

    default Order findOrderByName(String name) {
        var orderEntity = findByName(name);
        return OrderMapper.fromEntity(orderEntity);
    }

    //code is generated by Spring Boot Data Jpa
    OrderEntity findByName(String name);


}
